const SC_DAYTIME = 1;
const SC_OBJ_HAS_GOLD_NUM = 2;
const SC_LOCAL_FLAG_IS_SET = 3;
const SC_NUM_EQUALS_NUM = 4;
const SC_NUM_LESS_OR_EQUAL_NUM = 5;
const SC_PC_HAS_QUEST_IN_STATE = 6;
const SC_QUEST_IN_GLOBAL_STATE = 7;
const SC_OBJ_HAS_BLESS = 8;
const SC_OBJ_HAS_CURSE = 9;
const SC_NPC_OBJ_HAS_MET_PC_OBJ_BEFORE = 10;
const SC_OBJ_HAS_BAD_ASSOCIATES = 11;
const SC_OBJ_IS_POLYMORPHED = 12;
const SC_OBJ_IS_SHRUNK = 13;
const SC_OBJ_HAS_BODY_SPELL = 14;
const SC_OBJ_IS_INVISIBLE = 15;
const SC_OBJ_HAS_MIRROR_IMAGE = 16;
const SC_OBJ_HAS_ITEM_NAMED_OBJ = 17;
const SC_NPC_IS_A_FOLLOWER_OF_PC = 18;
const SC_NPC_OBJ_IS_A_MONSTER_OF_SPECIES = 19;
const SC_OBJ_IS_NAMED_NUM = 20;
const SC_OBJ_IS_WIELDING_ITEM = 21;
const SC_OBJ_IS_DEAD = 22;
const SC_OBJ_HAS_MAXIMUM_FOLLOWERS = 23;
const SC_OBJ_CAN_OPEN_THE_CONTAINER_OBJ = 24;
const SC_OBJ_HAS_SURRENDERED = 25;
const SC_OBJ_IS_IN_DIALOG = 26;
const SC_OBJ_IS_SWITCHED_OFF = 27;
const SC_OBJ_CAN_SEE_OBJ = 28;
const SC_OBJ_CAN_HEAR_OBJ = 29;
const SC_OBJ_IS_INVULNERABLE = 30;
const SC_OBJ_IS_IN_COMBAT = 31;
const SC_OBJ_IS_AT_LOCATION_XY = 32;
const SC_OBJ_HAS_REPUTATION_NUM = 33;
const SC_OBJ_IS_WITHIN_NUM_TILES_OF_LOCATION_XY = 34;
const SC_OBJ_IS_UNDER_THE_INFLUENCE_OF_SPELL_NUM = 35;
const SC_OBJ_IS_OPEN = 36;
const SC_OBJ_IS_AN_ANIMAL = 37;
const SC_OBJ_IS_UNDEAD = 38;
const SC_OBJ_WAS_JILTED_BY_A_PC = 39;
const SC_PC_OBJ_KNOWS_RUMOR_NUM = 40;
const SC_RUMOR_HAS_BEEN_QUELLED = 41;
const SC_OBJ_IS_BUSTED = 42;
const SC_GLOBAL_FLAG_NUM_IS_SET = 43;
const SC_OBJ_CAN_OPEN_THE_PORTAL_OBJ_IN_DIRECTION_NUM = 44;
const SC_SECTOR_AT_LOCATION_IS_BLOCKED = 45;
const SC_MONSTER_GENERATOR_IS_DISABLED = 46;
const SC_OBJ_IS_IDENTIFIED = 47;
const SC_OBJ_KNOWS_SPELL_NUM = 48;
const SC_OBJ_HAS_MASTERED_SPELL_COLLEGE_NUM = 49;
const SC_ITEMS_ARE_BEING_REWIELDED = 50;
const SC_OBJ_IS_PROWLING = 51;
const SC_OBJ_IS_WAITING_FOR_LEADERS_RETURN = 52;

function OpcodeConstantValueToString(id: integer): string;
begin
     case id of
1: 
result:='DAYTIME';
2: 
result:='OBJ_HAS_GOLD_NUM';
3: 
result:='LOCAL_FLAG_IS_SET';
4: 
result:='NUM_EQUALS_NUM';
5: 
result:='NUM_LESS_OR_EQUAL_NUM';
6: 
result:='PC_HAS_QUEST_IN_STATE';
7: 
result:='QUEST_IN_GLOBAL_STATE';
8: 
result:='OBJ_HAS_BLESS';
9: 
result:='OBJ_HAS_CURSE';
10: 
result:='NPC_OBJ_HAS_MET_PC_OBJ_BEFORE';
11: 
result:='OBJ_HAS_BAD_ASSOCIATES';
12: 
result:='OBJ_IS_POLYMORPHED';
13: 
result:='OBJ_IS_SHRUNK';
14: 
result:='OBJ_HAS_BODY_SPELL';
15: 
result:='OBJ_IS_INVISIBLE';
16: 
result:='OBJ_HAS_MIRROR_IMAGE';
17: 
result:='OBJ_HAS_ITEM_NAMED_OBJ';
18: 
result:='NPC_IS_A_FOLLOWER_OF_PC';
19: 
result:='NPC_OBJ_IS_A_MONSTER_OF_SPECIES';
20: 
result:='OBJ_IS_NAMED_NUM';
21: 
result:='OBJ_IS_WIELDING_ITEM';
22: 
result:='OBJ_IS_DEAD';
23: 
result:='OBJ_HAS_MAXIMUM_FOLLOWERS';
24: 
result:='OBJ_CAN_OPEN_THE_CONTAINER_OBJ';
25: 
result:='OBJ_HAS_SURRENDERED';
26: 
result:='OBJ_IS_IN_DIALOG';
27: 
result:='OBJ_IS_SWITCHED_OFF';
28: 
result:='OBJ_CAN_SEE_OBJ';
29: 
result:='OBJ_CAN_HEAR_OBJ';
30: 
result:='OBJ_IS_INVULNERABLE';
31: 
result:='OBJ_IS_IN_COMBAT';
32: 
result:='OBJ_IS_AT_LOCATION_XY';
33: 
result:='OBJ_HAS_REPUTATION_NUM';
34: 
result:='OBJ_IS_WITHIN_NUM_TILES_OF_LOCATION_XY';
35: 
result:='OBJ_IS_UNDER_THE_INFLUENCE_OF_SPELL_NUM';
36: 
result:='OBJ_IS_OPEN';
37: 
result:='OBJ_IS_AN_ANIMAL';
38: 
result:='OBJ_IS_UNDEAD';
39: 
result:='OBJ_WAS_JILTED_BY_A_PC';
40: 
result:='PC_OBJ_KNOWS_RUMOR_NUM';
41: 
result:='RUMOR_HAS_BEEN_QUELLED';
42: 
result:='OBJ_IS_BUSTED';
43: 
result:='GLOBAL_FLAG_NUM_IS_SET';
44: 
result:='OBJ_CAN_OPEN_THE_PORTAL_OBJ_IN_DIRECTION_NUM';
45: 
result:='SECTOR_AT_LOCATION_IS_BLOCKED';
46: 
result:='MONSTER_GENERATOR_IS_DISABLED';
47: 
result:='OBJ_IS_IDENTIFIED';
48: 
result:='OBJ_KNOWS_SPELL_NUM';
49: 
result:='OBJ_HAS_MASTERED_SPELL_COLLEGE_NUM';
50: 
result:='ITEMS_ARE_BEING_REWIELDED';
51: 
result:='OBJ_IS_PROWLING';
52: 
result:='OBJ_IS_WAITING_FOR_LEADERS_RETURN';
  end
end
