unit DLGCodes;




{ DLGCodes
  Version: 1.0 Release 0 Build 0
  ScriptEd Dialogue Codes Parser
  Date of Generation: 2.7.2008 19:17
  Author: T. Pitkänen
  (c) 2008 T. Pitkänen

  This unit was generated by Coco/R for Delphi (www.tetzel.com)  Any code in
  this file that you edit manually will be over-written when the file is
  regenerated.
}

interface
uses  SysUtils,Classes,CocoBase,mwStringHashList;



const
maxT = 28;
type
  SymbolSet = array[0..maxT div setsize] of TBitSet;

  EDLGCodes = class(Exception);
  TDLGCodes = class;

  TDLGCodesScanner = class(TCocoRScanner)
  private
    FOwner : TDLGCodes;
    fLastCommentList : TCommentList;
fHashList: TmwStringHashList;
procedure CheckLiteral(var Sym : integer);
function GetNextSymbolString: string;
    function Comment : boolean;
  protected
    procedure NextCh; override;
  public
    constructor Create;
destructor Destroy; override;

    procedure Get(var sym : integer); override; // Gets next symbol from source file

    property CurrentSymbol;
    property NextSymbol;
    property OnStatusUpdate;
    property Owner : TDLGCodes read fOwner write fOwner;
    property ScannerError;
    property SrcStream;
  end;  { TDLGCodesScanner }

  TDLGCodes = class(TCocoRGrammar)
  private
    { strictly internal variables }
    symSet : array[0..0] of SymbolSet; // symSet[0] = allSyncSyms
    fInternalGrammarComment : TCommentEvent;

    function GetMajorVersion : integer;
    function GetMinorVersion : integer;
    function GetRelease : integer;
    function GetBuild : integer;
    function GetBuildDate : TDateTime;
    function GetVersionComment : string;
    function GetGrammarAuthor : string;
    function GetGrammarCopyright : string;
    function GetVersion : String;
    procedure SetVersion(const Value : string);
    function _In(var s : SymbolSet; x : integer) : boolean;
    procedure InitSymSet;

    {Production methods}
    procedure _DLGCodes;
    procedure _ResultCode;
    procedure _operators;
    procedure _operator;
    procedure _UsageDefinition;

  private
    fOutputStream : TMemoryStream;
    fSubSelectDepth : integer;
    fInNaturalJoin : boolean;
            
    procedure Init;
    procedure Final;
                
    property OutputStream : TMemoryStream read fOutputStream write fOutputStream;
    
  protected
    { Protected Declarations }
    procedure Get; override;
    property InternalGrammarComment : TCommentEvent read fInternalGrammarComment write fInternalGrammarComment;
  public
    { Public Declarations }
    constructor Create(AOwner : TComponent); override;
    destructor Destroy; override;

    function ErrorStr(const ErrorCode : integer; const Data : string) : string; override;
    procedure Execute;
    function GetScanner : TDLGCodesScanner;
    procedure Parse;

    property ErrorList;
    property ListStream;
    property SourceStream;
    property Successful;
    property MajorVersion : integer read GetMajorVersion;
    property MinorVersion : integer read GetMinorVersion;
    property Release : integer read GetRelease;
    property Build : integer read GetBuild;
    property BuildDate : TDateTime read GetBuildDate;
    property VersionComment : string read GetVersionComment;
    property GrammarAuthor : string read GetGrammarAuthor;
    property GrammarCopyright : string read GetGrammarCopyright;

  published
    { Published Declarations }
    property AfterParse;
    property AfterGenList;
    property BeforeGenList;
    property BeforeParse;
    property ClearSourceStream;
    property GenListWhen;
    property SourceFileName;
property Version : string read GetVersion write SetVersion;

    property OnCustomError;
    property OnError;
    property OnFailure;
    property OnStatusUpdate;
    property OnSuccess;
  end; { TDLGCodes }

implementation



const

  EOFSYMB = 0;  identifierSym = 1;  numberSym = 2;  hexnumberSym = 3;
  _stringSym = 4;  charSym = 5;  _librarySym = 6;  PCSym = 7;  NPCSym = 8;
  _lessSym = 9;  _greaterSym = 10;  _plusSym = 11;  _minusSym = 12;
  _lbraceSym = 13;  _commaSym = 14;  _rbraceSym = 15;  RESULTCODESym = 16;
  USAGESym = 17;  _equalSym = 18;  _lparenSym = 19;  _rparenSym = 20;
  DESCRIPTIONSym = 21;  PARAMSSym = 22;  FORMATSym = 23;  CMDSym = 24;
  PARAM_oneSym = 25;  PARAM_twoSym = 26;  _semicolonSym = 27;  NOSYMB = 28;  _noSym = NOSYMB;   {error token code}

{ --------------------------------------------------------------------------- }
{ Arbitrary Code from ATG file }
const
  PadLen = 20;
                        
function PadR(S : string; Ch : char; L : integer) : string;
var
  i : integer;
begin
  for i := 1 to L - (Length(s)) do
    s := s + Ch;
  Result := s;
end;

procedure TDLGCodes.Init;
begin
  OutputStream.Clear;

 end;

procedure TDLGCodes.Final;
begin
   OutputStream.Position := 0;
  OutputStream.SaveToStream(ListStream);
  OutputStream.Clear;
end;
                                 

function parse_string(zstr: string): string;
var t:    integer;
var temp: string;
var len:  integer;
begin;
result:='';
  len := 0;
temp:='';
  //writeln ('Parsing string: ',zstr);
  t   := pos('"', zstr) + 1;
  len := length(zstr);
  while (zstr[t] <> '"') do
  begin;
    //writeln (zstr[t]);
    if (zstr[t] = '\') and (zstr[t + 1] = '"') then
    begin;
      temp := temp + '"';
      Inc(t, 1);
    end else
    if (zstr[t] = '\') and (zstr[t + 1] = '\') then
    begin;
      temp := temp + '\';
      Inc(t, 1);
    end else
    if (zstr[t] = '\') and (zstr[t + 1] = 't') then
    begin;
      temp := temp + #9;
      Inc(t, 1);
    end else
    if (zstr[t] = '\') and (zstr[t + 1] = 'n') then
    begin;
      temp := temp + #13#10;
      Inc(t, 1);
    end else

      temp := temp + zstr[t];

    Inc(t);
  end;
  Result := temp;
end;



(* End of Arbitrary Code *)



{ --------------------------------------------------------------------------- }
{ ---- implementation for TDLGCodesScanner ---- }

procedure TDLGCodesScanner.NextCh;
{ Return global variable ch }
begin
  LastInputCh := CurrInputCh;
  BufferPosition := BufferPosition + 1;
  SrcStream.Seek(BufferPosition,soFromBeginning);
  CurrInputCh := CurrentCh(BufferPosition);
  if (CurrInputCh = _EL) OR ((CurrInputCh = _LF) AND (LastInputCh <> _EL)) then
  begin
    CurrLine := CurrLine + 1;
    if Assigned(OnStatusUpdate) then
      OnStatusUpdate(Owner,IntToStr(CurrLine),CurrLine);
    StartOfLine := BufferPosition;
  end
end;  {NextCh}

function TDLGCodesScanner.Comment : boolean;
var
  level : integer;
  CommentColumn : integer;
  CommentLine : integer;
  oldLineStart : longint;
  CommentStr : string;
begin
  level := 1;
  oldLineStart := StartOfLine;
  CommentStr := CharAt(BufferPosition);
  CommentColumn := BufferPosition - StartOfLine - 1;
  CommentLine := CurrLine;
Result := false;
if (CurrInputCh = '/') then
  begin
NextCh;
CommentStr := CommentStr + CharAt(BufferPosition);
if (CurrInputCh = '*') then
begin
NextCh;
CommentStr := CommentStr + CharAt(BufferPosition);
while true do
begin
if (CurrInputCh = '*') then
begin
NextCh;
CommentStr := CommentStr + CharAt(BufferPosition);
if (CurrInputCh = '/') then
begin
level := level - 1;
NextCh;
CommentStr := CommentStr + CharAt(BufferPosition);
if level = 0 then
begin
  Result := true;
fLastCommentList.Add(CommentStr, CommentLine, CommentColumn);
  Exit;
end
end
end
else if CurrInputCh = _EF then
begin
  Result := false;
fLastCommentList.Add(CommentStr, CommentLine, CommentColumn);
  Exit;
end
else
begin
  NextCh;
  CommentStr := CommentStr + CharAt(BufferPosition);
end;
end; { WHILE TRUE }
end
else
begin
if (CurrInputCh = _CR) OR (CurrInputCh = _LF) then
begin
CurrLine := CurrLine - 1;
StartOfLine := oldLineStart
end;
BufferPosition := BufferPosition - 1;
CurrInputCh := LastInputCh;
Result := false;
end;
end;
end;  { Comment }

function TDLGCodesScanner.GetNextSymbolString: string;
var
  i: integer;
  q: integer;
begin
  Result := '';
  i := 1;
  q := bpCurrToken;
  while i <= NextSymbol.Len do
  begin
    Result := Result + CurrentCh(q);
    inc(q);
    inc(i);
  end;
end; {GetNextSymbolString}

procedure TDLGCodesScanner.CheckLiteral(var Sym : integer);
var
  SymId : integer;
  DefaultSymId : integer;
  aToken : string;
begin
  aToken := GetNextSymbolString;
  if fHashList.Hash(aToken, SymId, DefaultSymId) then
  begin
      sym := SymId;
  end;
end; {CheckLiteral}


procedure TDLGCodesScanner.Get(var sym : integer);
var
  state : integer;
begin   {Get}
while (CurrInputCh = ' ') OR
((CurrInputCh >= CHR(1)) AND (CurrInputCh <= ' ')) do
  NextCh;
if ((CurrInputCh = '/')) AND Comment then
begin
  Get(sym);
  exit;
  end;
  CurrentSymbol.pos := NextSymbol.Pos;
  NextSymbol.Pos := BufferPosition;
  CurrentSymbol.col := NextSymbol.Col;
  NextSymbol.Col := BufferPosition - StartOfLine;
  CurrentSymbol.line := NextSymbol.Line;
  NextSymbol.Line := CurrLine;
  CurrentSymbol.Len := NextSymbol.Len;
  NextSymbol.Len := 0;
  ContextLen := 0;
  state := StartState[ORD(CurrInputCh)];
  bpCurrToken := BufferPosition;
  while true do
  begin
    NextCh;
    NextSymbol.Len := NextSymbol.Len + 1;
    if BufferPosition > SrcStream.Size then
    begin
      sym := EOFSYMB;
      CurrInputCh := _EF;
      BufferPosition := BufferPosition - 1;
      exit
    end;
    case state of
   1: if ((CurrInputCh >= '0') AND (CurrInputCh <= '9') OR
(CurrInputCh >= 'A') AND (CurrInputCh <= 'Z') OR
(CurrInputCh = '_')) then
begin
 
end
else
begin
sym := identifierSym;
CheckLiteral(sym);
exit;
end;
   2: if ((CurrInputCh >= '0') AND (CurrInputCh <= '9')) then
begin
 
end
else if ((CurrInputCh = 'L') OR
(CurrInputCh = 'U')) then
begin
state := 15; 
end
else if (CurrInputCh = '.') then
begin
state := 3; 
end
else
begin
sym := numberSym;
exit;
end;
   3: if ((CurrInputCh >= '0') AND (CurrInputCh <= '9')) then
begin
 
end
else if ((CurrInputCh = 'L') OR
(CurrInputCh = 'U')) then
begin
state := 15; 
end
else
begin
sym := numberSym;
exit;
end;
   4: if ((CurrInputCh >= '0') AND (CurrInputCh <= '9') OR
(CurrInputCh >= 'A') AND (CurrInputCh <= 'F')) then
begin
state := 5; 
end
else
begin
  sym := _noSym;
exit;
end;
   5: if ((CurrInputCh >= '0') AND (CurrInputCh <= '9') OR
(CurrInputCh >= 'A') AND (CurrInputCh <= 'F')) then
begin
 
end
else if ((CurrInputCh = 'L') OR
(CurrInputCh = 'U')) then
begin
state := 16; 
end
else
begin
sym := hexnumberSym;
exit;
end;
   6: if ((CurrInputCh >= ' ') AND (CurrInputCh <= '!') OR
(CurrInputCh >= '#')) then
begin
 
end
else if (CurrInputCh = '"') then
begin
state := 7; 
end
else
begin
  sym := _noSym;
exit;
end;
   7: begin
sym := _stringSym;
exit;
end;
   8: if ((CurrInputCh >= ' ') AND (CurrInputCh <= '&') OR
(CurrInputCh >= '(') AND (CurrInputCh <= '[') OR
(CurrInputCh >= ']')) then
begin
state := 9; 
end
else if (CurrInputCh = '\') then
begin
state := 17; 
end
else
begin
  sym := _noSym;
exit;
end;
   9: if (CurrInputCh = CHR(39)) then
begin
state := 10; 
end
else
begin
  sym := _noSym;
exit;
end;
  10: begin
sym := charSym;
exit;
end;
  11: if ((CurrInputCh = '.') OR
(CurrInputCh >= '0') AND (CurrInputCh <= ':') OR
(CurrInputCh >= 'A') AND (CurrInputCh <= 'Z') OR
(CurrInputCh = '\')) then
begin
state := 12; 
end
else
begin
sym := _lessSym;
exit;
end;
  12: if ((CurrInputCh = '.') OR
(CurrInputCh >= '0') AND (CurrInputCh <= ':') OR
(CurrInputCh >= 'A') AND (CurrInputCh <= 'Z') OR
(CurrInputCh = '\')) then
begin
 
end
else if (CurrInputCh = '>') then
begin
state := 13; 
end
else
begin
  sym := _noSym;
exit;
end;
  13: begin
sym := _librarySym;
exit;
end;
  14: if ((CurrInputCh >= '0') AND (CurrInputCh <= '9')) then
begin
state := 2; 
end
else if ((CurrInputCh = 'L') OR
(CurrInputCh = 'U')) then
begin
state := 15; 
end
else if (CurrInputCh = '.') then
begin
state := 3; 
end
else if (CurrInputCh = 'X') then
begin
state := 4; 
end
else
begin
sym := numberSym;
exit;
end;
  15: begin
sym := numberSym;
exit;
end;
  16: begin
sym := hexnumberSym;
exit;
end;
  17: if ((CurrInputCh >= ' ') AND (CurrInputCh <= '&') OR
(CurrInputCh >= '(')) then
begin
state := 9; 
end
else if (CurrInputCh = CHR(39)) then
begin
state := 10; 
end
else
begin
  sym := _noSym;
exit;
end;
  18: begin
sym := _greaterSym;
exit;
end;
  19: begin
sym := _plusSym;
exit;
end;
  20: begin
sym := _minusSym;
exit;
end;
  21: begin
sym := _lbraceSym;
exit;
end;
  22: begin
sym := _commaSym;
exit;
end;
  23: begin
sym := _rbraceSym;
exit;
end;
  24: begin
sym := _equalSym;
exit;
end;
  25: begin
sym := _lparenSym;
exit;
end;
  26: begin
sym := _rparenSym;
exit;
end;
  27: begin
sym := _semicolonSym;
exit;
end;
  28: begin
sym := EOFSYMB;
CurrInputCh := #0;
BufferPosition := BufferPosition - 1;
exit
end;
    else
      begin
        sym := _noSym;
        EXIT;          // NextCh already done
      end;
    end;
  end;
end;  {Get}

constructor TDLGCodesScanner.Create;
begin
  inherited;
fHashList := TmwStringHashList.Create(ITinyHash, HashSecondaryOne, IHashCompare);
fHashList.AddString('CMD', CMDSym, CMDSym);
fHashList.AddString('DESCRIPTION', DESCRIPTIONSym, DESCRIPTIONSym);
fHashList.AddString('FORMAT', FORMATSym, FORMATSym);
fHashList.AddString('NPC', NPCSym, NPCSym);
fHashList.AddString('PARAM1', PARAM_oneSym, PARAM_oneSym);
fHashList.AddString('PARAM2', PARAM_twoSym, PARAM_twoSym);
fHashList.AddString('PARAMS', PARAMSSym, PARAMSSym);
fHashList.AddString('PC', PCSym, PCSym);
fHashList.AddString('RESULTCODE', RESULTCODESym, RESULTCODESym);
fHashList.AddString('USAGE', USAGESym, USAGESym);
fLastCommentList := TCommentList.Create;CurrentCh := CapChAt;
fStartState[  0] := 28; fStartState[  1] := 29; fStartState[  2] := 29; fStartState[  3] := 29; 
fStartState[  4] := 29; fStartState[  5] := 29; fStartState[  6] := 29; fStartState[  7] := 29; 
fStartState[  8] := 29; fStartState[  9] := 29; fStartState[ 10] := 29; fStartState[ 11] := 29; 
fStartState[ 12] := 29; fStartState[ 13] := 29; fStartState[ 14] := 29; fStartState[ 15] := 29; 
fStartState[ 16] := 29; fStartState[ 17] := 29; fStartState[ 18] := 29; fStartState[ 19] := 29; 
fStartState[ 20] := 29; fStartState[ 21] := 29; fStartState[ 22] := 29; fStartState[ 23] := 29; 
fStartState[ 24] := 29; fStartState[ 25] := 29; fStartState[ 26] := 29; fStartState[ 27] := 29; 
fStartState[ 28] := 29; fStartState[ 29] := 29; fStartState[ 30] := 29; fStartState[ 31] := 29; 
fStartState[ 32] := 29; fStartState[ 33] := 29; fStartState[ 34] :=  6; fStartState[ 35] := 29; 
fStartState[ 36] := 29; fStartState[ 37] := 29; fStartState[ 38] := 29; fStartState[ 39] :=  8; 
fStartState[ 40] := 25; fStartState[ 41] := 26; fStartState[ 42] := 29; fStartState[ 43] := 19; 
fStartState[ 44] := 22; fStartState[ 45] := 20; fStartState[ 46] := 29; fStartState[ 47] := 29; 
fStartState[ 48] := 14; fStartState[ 49] :=  2; fStartState[ 50] :=  2; fStartState[ 51] :=  2; 
fStartState[ 52] :=  2; fStartState[ 53] :=  2; fStartState[ 54] :=  2; fStartState[ 55] :=  2; 
fStartState[ 56] :=  2; fStartState[ 57] :=  2; fStartState[ 58] := 29; fStartState[ 59] := 27; 
fStartState[ 60] := 11; fStartState[ 61] := 24; fStartState[ 62] := 18; fStartState[ 63] := 29; 
fStartState[ 64] := 29; fStartState[ 65] :=  1; fStartState[ 66] :=  1; fStartState[ 67] :=  1; 
fStartState[ 68] :=  1; fStartState[ 69] :=  1; fStartState[ 70] :=  1; fStartState[ 71] :=  1; 
fStartState[ 72] :=  1; fStartState[ 73] :=  1; fStartState[ 74] :=  1; fStartState[ 75] :=  1; 
fStartState[ 76] :=  1; fStartState[ 77] :=  1; fStartState[ 78] :=  1; fStartState[ 79] :=  1; 
fStartState[ 80] :=  1; fStartState[ 81] :=  1; fStartState[ 82] :=  1; fStartState[ 83] :=  1; 
fStartState[ 84] :=  1; fStartState[ 85] :=  1; fStartState[ 86] :=  1; fStartState[ 87] :=  1; 
fStartState[ 88] :=  1; fStartState[ 89] :=  1; fStartState[ 90] :=  1; fStartState[ 91] := 29; 
fStartState[ 92] := 29; fStartState[ 93] := 29; fStartState[ 94] := 29; fStartState[ 95] :=  1; 
fStartState[ 96] := 29; fStartState[ 97] := 29; fStartState[ 98] := 29; fStartState[ 99] := 29; 
fStartState[100] := 29; fStartState[101] := 29; fStartState[102] := 29; fStartState[103] := 29; 
fStartState[104] := 29; fStartState[105] := 29; fStartState[106] := 29; fStartState[107] := 29; 
fStartState[108] := 29; fStartState[109] := 29; fStartState[110] := 29; fStartState[111] := 29; 
fStartState[112] := 29; fStartState[113] := 29; fStartState[114] := 29; fStartState[115] := 29; 
fStartState[116] := 29; fStartState[117] := 29; fStartState[118] := 29; fStartState[119] := 29; 
fStartState[120] := 29; fStartState[121] := 29; fStartState[122] := 29; fStartState[123] := 21; 
fStartState[124] := 29; fStartState[125] := 23; fStartState[126] := 29; fStartState[127] := 29; 
fStartState[128] := 29; fStartState[129] := 29; fStartState[130] := 29; fStartState[131] := 29; 
fStartState[132] := 29; fStartState[133] := 29; fStartState[134] := 29; fStartState[135] := 29; 
fStartState[136] := 29; fStartState[137] := 29; fStartState[138] := 29; fStartState[139] := 29; 
fStartState[140] := 29; fStartState[141] := 29; fStartState[142] := 29; fStartState[143] := 29; 
fStartState[144] := 29; fStartState[145] := 29; fStartState[146] := 29; fStartState[147] := 29; 
fStartState[148] := 29; fStartState[149] := 29; fStartState[150] := 29; fStartState[151] := 29; 
fStartState[152] := 29; fStartState[153] := 29; fStartState[154] := 29; fStartState[155] := 29; 
fStartState[156] := 29; fStartState[157] := 29; fStartState[158] := 29; fStartState[159] := 29; 
fStartState[160] := 29; fStartState[161] := 29; fStartState[162] := 29; fStartState[163] := 29; 
fStartState[164] := 29; fStartState[165] := 29; fStartState[166] := 29; fStartState[167] := 29; 
fStartState[168] := 29; fStartState[169] := 29; fStartState[170] := 29; fStartState[171] := 29; 
fStartState[172] := 29; fStartState[173] := 29; fStartState[174] := 29; fStartState[175] := 29; 
fStartState[176] := 29; fStartState[177] := 29; fStartState[178] := 29; fStartState[179] := 29; 
fStartState[180] := 29; fStartState[181] := 29; fStartState[182] := 29; fStartState[183] := 29; 
fStartState[184] := 29; fStartState[185] := 29; fStartState[186] := 29; fStartState[187] := 29; 
fStartState[188] := 29; fStartState[189] := 29; fStartState[190] := 29; fStartState[191] := 29; 
fStartState[192] := 29; fStartState[193] := 29; fStartState[194] := 29; fStartState[195] := 29; 
fStartState[196] := 29; fStartState[197] := 29; fStartState[198] := 29; fStartState[199] := 29; 
fStartState[200] := 29; fStartState[201] := 29; fStartState[202] := 29; fStartState[203] := 29; 
fStartState[204] := 29; fStartState[205] := 29; fStartState[206] := 29; fStartState[207] := 29; 
fStartState[208] := 29; fStartState[209] := 29; fStartState[210] := 29; fStartState[211] := 29; 
fStartState[212] := 29; fStartState[213] := 29; fStartState[214] := 29; fStartState[215] := 29; 
fStartState[216] := 29; fStartState[217] := 29; fStartState[218] := 29; fStartState[219] := 29; 
fStartState[220] := 29; fStartState[221] := 29; fStartState[222] := 29; fStartState[223] := 29; 
fStartState[224] := 29; fStartState[225] := 29; fStartState[226] := 29; fStartState[227] := 29; 
fStartState[228] := 29; fStartState[229] := 29; fStartState[230] := 29; fStartState[231] := 29; 
fStartState[232] := 29; fStartState[233] := 29; fStartState[234] := 29; fStartState[235] := 29; 
fStartState[236] := 29; fStartState[237] := 29; fStartState[238] := 29; fStartState[239] := 29; 
fStartState[240] := 29; fStartState[241] := 29; fStartState[242] := 29; fStartState[243] := 29; 
fStartState[244] := 29; fStartState[245] := 29; fStartState[246] := 29; fStartState[247] := 29; 
fStartState[248] := 29; fStartState[249] := 29; fStartState[250] := 29; fStartState[251] := 29; 
fStartState[252] := 29; fStartState[253] := 29; fStartState[254] := 29; fStartState[255] := 29; 
end; {Create}

destructor TDLGCodesScanner.Destroy;
begin
  fHashList.Free;
  fHashList := NIL;
  if Assigned(fLastCommentList) then
  begin
    fLastCommentList.Free;
    fLastCommentList := NIL;
  end;
  inherited;
end;

{ --------------------------------------------------------------------------- }
{ ---- implementation for TDLGCodes ---- }

constructor TDLGCodes.Create(AOwner : TComponent);
begin
  inherited;
  Scanner := TDLGCodesScanner.Create;
  GetScanner.Owner := self;
fOutputStream := TMemoryStream.Create;
  
  InitSymSet;
end; {Create}

destructor TDLGCodes.Destroy;
begin
  Scanner.Free;
fOutputStream.Free;
  
  inherited;
end; {Destroy}

function TDLGCodes.ErrorStr(const ErrorCode : integer; const Data : string) : string;
begin
  case ErrorCode of
       0 : Result := 'EOF expected';
   1 : Result := 'identifier expected';
   2 : Result := 'number expected';
   3 : Result := 'hexnumber expected';
   4 : Result := '_string expected';
   5 : Result := 'char expected';
   6 : Result := '_library expected';
   7 : Result := '"PC" expected';
   8 : Result := '"NPC" expected';
   9 : Result := '"<" expected';
  10 : Result := '">" expected';
  11 : Result := '"+" expected';
  12 : Result := '"-" expected';
  13 : Result := '"{" expected';
  14 : Result := '"," expected';
  15 : Result := '"}" expected';
  16 : Result := '"RESULTCODE" expected';
  17 : Result := '"USAGE" expected';
  18 : Result := '"=" expected';
  19 : Result := '"(" expected';
  20 : Result := '")" expected';
  21 : Result := '"DESCRIPTION" expected';
  22 : Result := '"PARAMS" expected';
  23 : Result := '"FORMAT" expected';
  24 : Result := '"CMD" expected';
  25 : Result := '"PARAM1" expected';
  26 : Result := '"PARAM2" expected';
  27 : Result := '";" expected';
  28 : Result := 'not expected';
  29 : Result := 'invalid operator';
  30 : Result := 'invalid UsageDefinition';


  else
    if Assigned(OnCustomError) then
      Result := OnCustomError(Self, ErrorCode, Data)
    else
    begin
      Result := 'Error: ' + IntToStr(ErrorCode);
      if Trim(Data) > '' then
        Result := Result + ' (' + Data + ')';
    end;
  end;  {case nr}
end; {ErrorStr}

procedure TDLGCodes.Execute;
begin
  ClearErrors;
  ListStream.Clear;
  Extra := 1;

  { if there is a file name then load the file }
  if Trim(SourceFileName) <> '' then
  begin
    GetScanner.SrcStream.Clear;
    GetScanner.SrcStream.LoadFromFile(SourceFileName);
  end;

  { install error reporting procedure }
  GetScanner.ScannerError := StoreError;

  if Assigned(OnStatusUpdate) then
    OnStatusUpdate(Self,'parsing source',-1);

  { instigate the compilation }
  if Assigned(BeforeParse) then
    BeforeParse(Self);
  Parse;
  if Assigned(AfterParse) then
    AfterParse(Self);

  { generate the source listing to the ListStream }
  if (GenListWhen = glAlways) OR ((GenListWhen = glOnError) AND (ErrorList.Count > 0)) then
    GenerateListing;
  if ClearSourceStream then
    GetScanner.SrcStream.Clear;
  ListStream.Position := 0;  // goto the beginning of the stream
  if Successful AND Assigned(OnSuccess) then
    OnSuccess(Self);
  if (NOT Successful) AND Assigned(OnFailure) then
    OnFailure(Self, ErrorList.Count);
end;  {Execute}

procedure TDLGCodes.Get;
begin
  repeat

if GetScanner.fLastCommentList.Count > 0 then
begin
  if Assigned(fInternalGrammarComment) then
    fInternalGrammarComment(Self,GetScanner.fLastCommentList);
  GetScanner.fLastCommentList.Clear;
end;

    GetScanner.Get(fCurrentInputSymbol);
    if fCurrentInputSymbol <= maxT then
      errDist := errDist + 1
    else
    begin
    end;
  until fCurrentInputSymbol <= maxT;
end;  {Get}

function TDLGCodes.GetScanner : TDLGCodesScanner;
begin
  Result := Scanner AS TDLGCodesScanner;
end; {GetScanner}

function TDLGCodes._In(var s : SymbolSet; x : integer) : boolean;
begin
  _In := x mod setsize in s[x div setsize];
end;  {_In}

procedure TDLGCodes._DLGCodes;begin
_ResultCode;
while (fCurrentInputSymbol = RESULTCODESym) do begin
_ResultCode;
end;
end;

procedure TDLGCodes._ResultCode;begin
Expect(RESULTCODESym);
Expect(_stringSym);
writeln('result  code:  ',parse_string(lexstring)  );
Expect(USAGESym);
Expect(_equalSym);
Expect(_lparenSym);
_UsageDefinition;
while (fCurrentInputSymbol = _commaSym) do begin
Get;
_UsageDefinition;
end;
Expect(_rparenSym);
Expect(DESCRIPTIONSym);
Expect(_equalSym);
Expect(_stringSym);
writeln('description:  ',parse_string(lexstring)  );
Expect(PARAMSSym);
Expect(_equalSym);
Expect(numberSym);
writeln('number  of  params:  ',lexstring);
Expect(FORMATSym);
Expect(_equalSym);
Expect(_lparenSym);
Expect(CMDSym);
if (fCurrentInputSymbol = _lbraceSym) then begin
_operators;
end;
if (fCurrentInputSymbol = PARAM_oneSym) then begin
Get;
end;
if (fCurrentInputSymbol = PARAM_twoSym) then begin
Get;
end;
Expect(_rparenSym);
Expect(_semicolonSym);
end;

procedure TDLGCodes._operators;begin
Expect(_lbraceSym);
_operator;
while (fCurrentInputSymbol = _commaSym) do begin
Get;
_operator;
end;
Expect(_rbraceSym);
end;

procedure TDLGCodes._operator;begin
if (fCurrentInputSymbol = _lessSym) then begin
Get;
end else if (fCurrentInputSymbol = _greaterSym) then begin
Get;
end else if (fCurrentInputSymbol = _plusSym) then begin
Get;
end else if (fCurrentInputSymbol = _minusSym) then begin
Get;
end else begin SynError(29);
end;
writeln('operator:  ',lexstring);
end;

procedure TDLGCodes._UsageDefinition;begin
if (fCurrentInputSymbol = PCSym) then begin
Get;
end else if (fCurrentInputSymbol = NPCSym) then begin
Get;
end else begin SynError(30);
end;
writeln('USAGE:',lexstring);
if GetScanner.fLastCommentList.Count > 0 then
begin
  if Assigned(fInternalGrammarComment) then
    fInternalGrammarComment(Self,GetScanner.fLastCommentList);
  GetScanner.fLastCommentList.Clear;
end;
end;

function TDLGCodes.GetMajorVersion : integer;
begin
  Result := 1;
end;

function TDLGCodes.GetMinorVersion : integer;
begin
  Result := 0;
end;

function TDLGCodes.GetRelease : integer;
begin
  Result := 0;
end;

function TDLGCodes.GetBuild : integer;
begin
  Result := 0;
end;

function TDLGCodes.GetBuildDate : TDateTime;
const
  BDate = 39631;
  Hour = 19;
  Min = 17;
begin
  Result := BDate + EncodeTime(Hour, Min, 0 ,0);
end;

function TDLGCodes.GetVersion : string;
var
  MinorVersionStr : string;
begin
  MinorVersionStr := IntToStr(MinorVersion);
  if (length(MinorVersionStr) > 0) AND (MinorVersion > 0) then
    MinorVersionStr := '0' + MinorVersionStr;
  Result := 'Version: ' + IntToStr(MajorVersion) + '.' + MinorVersionStr + ' Release '
     + IntToStr(Release) + ' Build ' + IntToStr(Build);
end;

function TDLGCodes.GetVersionComment : string;
begin
  Result := 'ScriptEd Dialogue Codes Parser';
end;

function TDLGCodes.GetGrammarAuthor : string;
begin
  Result := 'T. Pitkänen';
end;

function TDLGCodes.GetGrammarCopyright : string;
begin
  Result := '(c) 2008 T. Pitkänen';
end;

procedure TDLGCodes.SetVersion(const Value : string);
begin
  // This is a read only property. However, we want the value
  // to appear in the Object Inspector during design time.
end;

procedure TDLGCodes.Parse;
begin
  errDist := minErrDist;
GetScanner._Reset;
Get;
_DLGCodes;
end;  {Parse}

procedure TDLGCodes.InitSymSet;
begin
symSet[ 0, 0] := [EOFSYMB];
symSet[ 0, 1] := [];
end; {InitSymSet}

end { DLGCodes }.    
