(*
  Simple library for generating ollama requests

  Generated by ChatGPT
  debugged properly so it freaking works

  supports asynchronous prompting that runs in a separate thread

  Extended to support OllamaCloud with API key authentication
*)
unit OllamaLib;

interface

uses
  System.SysUtils, System.threading, arcanumscrlib, System.Classes,
  winapi.windows, System.JSON, System.Net.HttpClient, System.Net.URLClient,
  System.Net.HttpClientComponent;

type
  TGenerateTextCallback = reference to procedure(const Response: string;
    const Error: string);

  TOllamaAPIBase = class
  public
    function GenerateText(const Model, Prompt: string; Temperature: Double = 0.7; MaxTokens: Integer = 100): string; virtual; abstract;
    function ListModels: TStringList; virtual; abstract;
    function IsServerRunning: Boolean; virtual; abstract;
    procedure GenerateTextAsync(const Prompt, Model: string; Callback: TGenerateTextCallback); virtual; abstract;
  end;

  TOllamaLocalAPI = class(TOllamaAPIBase)
  private
    FBaseUrl: string;
    FHttpClient: TNetHTTPClient;
    function SendGetRequest(const Endpoint: string;
      out ResponseContent: string): Boolean;
  public
    constructor Create(const ABaseUrl: string);
    destructor Destroy; override;
    function ListModels: TStringList; override;
    function GenerateText(const Model, Prompt: string; Temperature: Double = 0.7; MaxTokens: Integer = 100): string; override;
    function IsServerRunning: Boolean; override;
    procedure GenerateTextAsync(const Prompt, Model: string;
      Callback: TGenerateTextCallback); override;
    procedure RunGenerateText(const Model, Prompt: string;
      Callback: TGenerateTextCallback);
  end;

  TOllamaCloudAPI = class(TOllamaAPIBase)
  private
    FBaseUrl: string;
    FApiKey: string;
    FHttpClient: TNetHTTPClient;
    function SendGetRequest(const Endpoint: string; out ResponseContent: string): Boolean;
    function SendPostRequest(const Endpoint: string; RequestJson: TJSONObject;
      out ResponseContent: string): Boolean;
  public
    constructor Create(const ABaseUrl, AApiKey: string);
    destructor Destroy; override;
    function ListModels: TStringList; override;
    function GenerateText(const Model, Prompt: string; Temperature: Double = 0.7; MaxTokens: Integer = 100): string; override;
    function IsServerRunning: Boolean; override;
    procedure GenerateTextAsync(const Prompt, Model: string;
      Callback: TGenerateTextCallback); override;
    procedure RunGenerateText(const Model, Prompt: string;
      Callback: TGenerateTextCallback);
  end;

implementation

{ TOllamaLocalAPI }

constructor TOllamaLocalAPI.Create(const ABaseUrl: string);
begin
  inherited Create;
  FBaseUrl := ABaseUrl;
  FHttpClient := TNetHTTPClient.Create(nil);
end;

destructor TOllamaLocalAPI.Destroy;
begin
  FHttpClient.Free;
  inherited;
end;

function TOllamaLocalAPI.SendGetRequest(const Endpoint: string;
  out ResponseContent: string): Boolean;
var
  HttpClient: THttpClient;
  Response: IHTTPResponse;
begin
  Result := False;
  HttpClient := THttpClient.Create;
  try
    try
      Response := HttpClient.Get(FBaseUrl + Endpoint);
      if Response.StatusCode = 200 then
      begin
        ResponseContent := Response.ContentAsString(TEncoding.UTF8);
        Result := True;
      end
      else
        ResponseContent := Format('Error: %d - %s',
          [Response.StatusCode, Response.StatusText]);
    except
      on E: Exception do
        ResponseContent := 'Exception: ' + E.Message;
    end;
  finally
    HttpClient.Free;
  end;
end;

function TOllamaLocalAPI.IsServerRunning: Boolean;
var
  ResponseContent: string;
begin
  Result := SendGetRequest('/', ResponseContent);
end;

function TOllamaLocalAPI.ListModels: TStringList;
var
  Response: IHTTPResponse;
  ResponseStr: string;
  ResponseJson: TJSONValue;
  TagsArray: TJSONArray;
  TagObject: TJSONObject;
  ModelName: string;
  i: Integer;
begin
  Result := TStringList.Create;
  try
    Response := FHttpClient.Get(FBaseUrl + '/api/tags');
    ResponseStr := Response.ContentAsString(TEncoding.UTF8);

    if Trim(ResponseStr) = '' then
    begin
      Result.Add('Error: Response body is empty.');
      Exit;
    end;

    try
      ResponseJson := TJSONObject.ParseJSONValue(ResponseStr);
      if Assigned(ResponseJson) and (ResponseJson is TJSONObject) then
      begin
        TagsArray := (ResponseJson as TJSONObject).GetValue<TJSONArray>('models');
        if Assigned(TagsArray) then
        begin
          for i := 0 to TagsArray.Count - 1 do
          begin
            TagObject := TagsArray.Items[i] as TJSONObject;
            if Assigned(TagObject) then
            begin
              ModelName := TagObject.GetValue<string>('model');
              if Trim(ModelName) <> '' then
                Result.Add(ModelName);
            end;
          end;
        end
        else
          Result.Add('Error: No models found in response.');
      end
      else
        Result.Add('Error: JSON structure unexpected or missing "models" key.');
    finally
      ResponseJson.Free;
    end;
  except
    on E: Exception do
      Result.Add('Error: ' + E.Message);
  end;
end;

function TOllamaLocalAPI.GenerateText(const Model, Prompt: string; Temperature: Double = 0.7; MaxTokens: Integer = 100): string;
var
  Response: IHTTPResponse;
  RequestJson: TJSONObject;
  ResponseJson: TJSONValue;
  ResponseStr: string;
  StringList: TStringList;
begin
  consoledebug('Starting ollama generate....');
  Result := '';
  try
    RequestJson := TJSONObject.Create;
    try
      RequestJson.AddPair('model', Model);
      RequestJson.AddPair('prompt', Prompt);
      RequestJson.AddPair('stream', TJSONFalse.Create);
      RequestJson.AddPair('temperature', TJSONNumber.Create(Temperature));
      RequestJson.AddPair('num_predict', TJSONNumber.Create(MaxTokens));

      consoledebug('Posting...');
      Response := FHttpClient.Post(FBaseUrl + '/api/generate',
        TStringStream.Create(RequestJson.ToString, TEncoding.UTF8), nil,
        [TNameValuePair.Create('Content-Type', 'application/json')]);

      ResponseStr := Response.ContentAsString(TEncoding.UTF8);
      if Trim(ResponseStr) = '' then
      begin
        Result := 'Error: Response body is empty.';
        Exit;
      end;

      if Copy(ResponseStr, 1, 1) <> '{' then
      begin
        Result := ResponseStr;
        Exit;
      end;

      try
        ResponseJson := TJSONObject.ParseJSONValue(ResponseStr);
        if Assigned(ResponseJson) and (ResponseJson is TJSONObject) then
        begin
          Result := (ResponseJson as TJSONObject).GetValue<string>('response');
          StringList := TStringList.Create;
          try
            StringList.Text := Result;
            Result := StringList.Text;
          finally
            StringList.Free;
          end;
        end
        else
          Result := 'Error: JSON structure unexpected or missing key "response".';
      finally
        ResponseJson.Free;
      end;
    finally
      RequestJson.Free;
    end;
  except
    on E: Exception do
      Result := 'Error: ' + E.Message;
  end;
end;

procedure TOllamaLocalAPI.RunGenerateText(const Model, Prompt: string;
  Callback: TGenerateTextCallback);
var
  HttpClient: THttpClient;
  RequestBody: TStringStream;
  Response: IHTTPResponse;
  StringList: TStringList;
  JSONRequest, JSONResponse: TJSONObject;
  ResponseText, ErrorMessage, DebugMessage: string;
begin
  ResponseText := '';
  ErrorMessage := '';

  if FBaseUrl = '' then
  begin
    ErrorMessage := 'Error: Base URL is not initialized.';
    if Assigned(Callback) then
      TThread.Queue(nil,
        procedure
        begin
          Callback('', ErrorMessage);
        end);
    Exit;
  end;

  HttpClient := THttpClient.Create;
  try
    JSONRequest := TJSONObject.Create;
    try
      JSONRequest.AddPair('prompt', Prompt);
      JSONRequest.AddPair('model', Model);
      JSONRequest.AddPair('stream', TJSONFalse.Create);

      DebugMessage := 'Debug: Sending request to ' + FBaseUrl +
        '/api/generate payload: ' + JSONRequest.ToJSON;
      TThread.Queue(nil,
        procedure
        begin
          consoledebug(DebugMessage);
        end);

      RequestBody := TStringStream.Create(JSONRequest.ToJSON, TEncoding.UTF8);
      try
        try
          Response := HttpClient.Post(FBaseUrl + '/api/generate', RequestBody,
            nil, [TNameValuePair.Create('Content-Type', 'application/json')]);
          if Response.StatusCode = 200 then
          begin
            JSONResponse := TJSONObject.ParseJSONValue
              (Response.ContentAsString(TEncoding.UTF8)) as TJSONObject;
            try
              ResponseText := JSONResponse.GetValue<string>('response');
              StringList := TStringList.Create;
              try
                StringList.Text := ResponseText;
                ResponseText := StringList.Text;
              finally
                StringList.Free;
              end;
            finally
              JSONResponse.Free;
            end;
          end
          else
            ErrorMessage := Format('HTTP Error %d: %s',
              [Response.StatusCode, Response.StatusText]);
        except
          on E: Exception do
            ErrorMessage := 'Exception: ' + E.Message;
        end;
      finally
        RequestBody.Free;
      end;
    finally
      JSONRequest.Free;
    end;
  finally
    HttpClient.Free;
  end;

  if Assigned(Callback) then
  begin
    TThread.Queue(nil,
      procedure
      begin
        Callback(ResponseText, ErrorMessage);
      end);
  end;
end;

procedure TOllamaLocalAPI.GenerateTextAsync(const Prompt, Model: string;
  Callback: TGenerateTextCallback);
begin
  TTask.Run(
    procedure
    begin
      RunGenerateText(Prompt, Model, Callback);
    end);
end;

{ TOllamaCloudAPI }

constructor TOllamaCloudAPI.Create(const ABaseUrl, AApiKey: string);
begin
  inherited Create;
  FBaseUrl := ABaseUrl;
  FApiKey := AApiKey;
  FHttpClient := TNetHTTPClient.Create(nil);
end;

destructor TOllamaCloudAPI.Destroy;
begin
  FHttpClient.Free;
  inherited;
end;

function TOllamaCloudAPI.SendGetRequest(const Endpoint: string;
  out ResponseContent: string): Boolean;
var
  Response: IHTTPResponse;
begin
  Result := False;
  try
    Response := FHttpClient.Get(FBaseUrl + Endpoint, nil,
      [TNameValuePair.Create('Authorization', 'Bearer ' + FApiKey)]);
    if Response.StatusCode = 200 then
    begin
      ResponseContent := Response.ContentAsString(TEncoding.UTF8);
      Result := True;
    end
    else
      ResponseContent := Format('Error: %d - %s',
        [Response.StatusCode, Response.StatusText]);
  except
    on E: Exception do
      ResponseContent := 'Exception: ' + E.Message;
  end;
end;

function TOllamaCloudAPI.SendPostRequest(const Endpoint: string;
  RequestJson: TJSONObject; out ResponseContent: string): Boolean;
var
  Response: IHTTPResponse;
  RequestStream: TStringStream;
begin
  Result := False;
  RequestStream := TStringStream.Create(RequestJson.ToString, TEncoding.UTF8);
  try
    try
      Response := FHttpClient.Post(FBaseUrl + Endpoint, RequestStream, nil,
        [TNameValuePair.Create('Content-Type', 'application/json'),
         TNameValuePair.Create('Authorization', 'Bearer ' + FApiKey)]);
      if Response.StatusCode = 200 then
      begin
        ResponseContent := Response.ContentAsString(TEncoding.UTF8);
        Result := True;
      end
      else
        ResponseContent := Format('Error: %d - %s',
          [Response.StatusCode, Response.StatusText]);
    except
      on E: Exception do
        ResponseContent := 'Exception: ' + E.Message;
    end;
  finally
    RequestStream.Free;
  end;
end;

function TOllamaCloudAPI.IsServerRunning: Boolean;
var
  ResponseContent: string;
begin
  Result := SendGetRequest('/', ResponseContent);
end;

function TOllamaCloudAPI.ListModels: TStringList;
var
  ResponseStr: string;
  ResponseJson: TJSONValue;
  ModelsArray: TJSONArray;
  ModelObject: TJSONObject;
  ModelName: string;
  i: Integer;
begin
  Result := TStringList.Create;
  try
    if not SendGetRequest('/api/tags', ResponseStr) then
    begin
      Result.Add('Error: ' + ResponseStr);
      Exit;
    end;

    if Trim(ResponseStr) = '' then
    begin
      Result.Add('Error: Response body is empty.');
      Exit;
    end;

    try
      ResponseJson := TJSONObject.ParseJSONValue(ResponseStr);
      if Assigned(ResponseJson) and (ResponseJson is TJSONObject) then
      begin
        ModelsArray := (ResponseJson as TJSONObject).GetValue<TJSONArray>('models');
        if Assigned(ModelsArray) then
        begin
          for i := 0 to ModelsArray.Count - 1 do
          begin
            ModelObject := ModelsArray.Items[i] as TJSONObject;
            if Assigned(ModelObject) then
            begin
              ModelName := ModelObject.GetValue<string>('model');
              if Trim(ModelName) <> '' then
                Result.Add(ModelName);
            end;
          end;
        end
        else
          Result.Add('Error: No models array in response.');
      end
      else
        Result.Add('Error: Invalid JSON response.');
    finally
      ResponseJson.Free;
    end;
  except
    on E: Exception do
      Result.Add('Error: ' + E.Message);
  end;
end;

function TOllamaCloudAPI.GenerateText(const Model, Prompt: string; Temperature: Double = 0.7; MaxTokens: Integer = 100): string;
var
  RequestJson: TJSONObject;
  ResponseStr: string;
  ResponseJson: TJSONValue;
  StringList: TStringList;
begin
  Result := '';
  RequestJson := TJSONObject.Create;
  try
    RequestJson.AddPair('model', Model);
    RequestJson.AddPair('prompt', Prompt);
    RequestJson.AddPair('stream', TJSONFalse.Create);
    RequestJson.AddPair('temperature', TJSONNumber.Create(Temperature));
    RequestJson.AddPair('num_predict', TJSONNumber.Create(MaxTokens));

    if not SendPostRequest('/api/generate', RequestJson, ResponseStr) then
    begin
      Result := 'Error: Request failed - ' + ResponseStr;
      Exit;
    end;

    if Trim(ResponseStr) = '' then
    begin
      Result := 'Error: Response body is empty.';
      Exit;
    end;

    if Copy(ResponseStr, 1, 1) <> '{' then
    begin
      Result := ResponseStr;
      Exit;
    end;

    try
      ResponseJson := TJSONObject.ParseJSONValue(ResponseStr);
      if Assigned(ResponseJson) and (ResponseJson is TJSONObject) then
      begin
        Result := (ResponseJson as TJSONObject).GetValue<string>('response');
        StringList := TStringList.Create;
        try
          StringList.Text := Result;
          Result := StringList.Text;
        finally
          StringList.Free;
        end;
      end
      else
        Result := 'Error: Unexpected JSON structure.';
    finally
      ResponseJson.Free;
    end;
  finally
    RequestJson.Free;
  end;
end;

procedure TOllamaCloudAPI.RunGenerateText(const Model, Prompt: string;
  Callback: TGenerateTextCallback);
var
  ResponseText, ErrorMessage: string;
begin
  ResponseText := '';
  ErrorMessage := '';

  if FBaseUrl = '' then
  begin
    ErrorMessage := 'Error: Base URL is not initialized.';
    if Assigned(Callback) then
      TThread.Queue(nil,
        procedure
        begin
          Callback('', ErrorMessage);
        end);
    Exit;
  end;

  try
    ResponseText := GenerateText(Model, Prompt);
    if Pos('Error:', ResponseText) = 1 then
      ErrorMessage := ResponseText;
  except
    on E: Exception do
      ErrorMessage := 'Exception: ' + E.Message;
  end;

  if Assigned(Callback) then
  begin
    TThread.Queue(nil,
      procedure
      begin
        Callback(ResponseText, ErrorMessage);
      end);
  end;
end;

procedure TOllamaCloudAPI.GenerateTextAsync(const Prompt, Model: string;
  Callback: TGenerateTextCallback);
begin
  TTask.Run(
    procedure
    begin
      RunGenerateText(Prompt, Model, Callback);
    end);
end;

end.
